name: 'Go linter Runner'
description: 'Run linter on github repo and comment issue'
author: 'alingse'
inputs:
  go_version:
    description: |
      Go Version
      Default '1.22'
    default: 1.22
  workdir:
    description: |
      Work directory.
      Default '.'
    default: '.'
  install_command:
    description: |
      The install command like 'go install xxx/xxx@yyy'
    required: true
  linter_command:
    description: |
      The lint command to run linter like 'xxlint --yy cc'
    required: true
  repo_url:
    description: |
      The repo to run lint, only work for github repo now
    required: true
  excludes:
    description: |
      The output must exclude string array, can set as regex
    type: array
    default: []
  includes:
    description: |
      The output must include string array, can set as regex
    type: array
    default: '[]'
  issue_id:
    description: |
      If linter catch some output, it will post comment on the issue
    default: ''
  GH_TOKEN:
    description: |
      If enabled issue_id, must set GH_TOKEN
    default: ''

runs:
  using: "composite"
  steps:
    - name: Test command
      run: gh issue list
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}

    - name: Setup Go environment
      uses: actions/setup-go@v3.2.0
      with:
        go-version: ${{ inputs.go_version }}

    - name: Build Go executable
      run: |
        ls -lh $GITHUB_ACTION_PATH
        cd $GITHUB_ACTION_PATH
        go build -o go-linter-runner main.go
        mv go-linter-runner /usr/local/bin/go-linter-runner
      shell: bash

    - name: Run the executable
      run: go-linter-runner '${{ toJson(inputs) }}'
      shell: bash
      env:
        GH_ACTION_LINK: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

branding:
  icon: 'check'
  color: 'blue'
