name: 'Go linter Runner'
description: 'Run linter on github repo and comment issue'
author: 'alingse'
inputs:
  go_version:
    description: |
      Go Version
      Default '1.22'
    default: 1.22
  action:
    description: |
      'run' or 'submit'
      Default 'run'
    default: 'run'
  json_config:
    description: |
      the json style config file
    default: ''
  yaml_config:
    description: |
      the yaml style config file
    default: ''
  workdir:
    description: |
      Work directory.
      Default '.'
    default: '.'
  install_command:
    description: |
      The install command like 'go install xxx/xxx@yyy'
  linter_command:
    description: |
      The lint command to run linter like 'xxlint --yy cc'
  repo_url:
    description: |
      The repo to run lint, only work for github repo now
    required: true
  excludes:
    description: |
      The output must exclude string array, can set as regex
    default: '[]'
  includes:
    description: |
      The output must include string array, can set as regex
    default: '[ ".go" ]'
  issue_id:
    description: |
      If linter catch some output, it will post comment on the issue
    default: ''

runs:
  using: "composite"
  steps:
    - name: Setup Go environment
      uses: actions/setup-go@v3.2.0
      with:
        go-version: ${{ inputs.go_version }}

    - name: Build go-linter-runner
      run: |
        cd $GITHUB_ACTION_PATH
        go build -o /usr/local/bin/go-linter-runner main.go
      shell: bash

    - name: Run go-linter-runner
      run: go-linter-runner run --json '${{ toJson(inputs) }}'
      shell: bash
      env:
        GH_ACTION_LINK: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

branding:
  icon: 'check'
  color: 'blue'
