workdir: '.'
install_command: go install github.com/alingse/sundrylint/cmd/sundrylint@latest
linter_command: sundrylint
includes: ["some case"]
excludes: ["some unexpected case"]
issue_id: 2
enable_testfile: false
