name: check-repo
run-name: "run `makezero` for ${{github.event.inputs.repo_url}}"

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: "the repo to check"
        default: "https://github.com/alingse/makezero"
        required: true

permissions:
  issues: write

jobs:
  go-linter-runner-for-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: alingse/go-linter-runner@main
        with:
          install_command: go install github.com/alingse/makezero@f6a823578e89de5cdfdfef50d4a5d9a09ade16dd
          linter_command: makezero
          repo_url: https://github.com/alingse/makezero
          includes: '["go", "github"]'
          issue_id: 1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
