name: Check Repo with linter
run-name: "check repo ${{ github.event.inputs.repo_url }}"

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: "Any Github Golang Repo link"
        default: ""
        required: true

jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v3.2.0
        with:
          go-version: 1.22

      - name: Install
        run: go install github.com/alingse/makezero@fix-with-copy-and-go-mod

      - name: Git Clone
        run: git clone "${{ github.event.inputs.repo_url }}"

      - name: List
        run: ls && echo "${{ github.event.inputs.repo_url }}"

      - name: Check And Build
        id: check_go_mod
        run: |
          cd `ls`

          ls go.mod

          go mod tidy

          exit `go build ./... 2>&1|grep -c warning`
        continue-on-error: true

      - name: Run asasalint
        if: steps.check_go_mod.outcome == 'success'
        run: |
          cd `ls`

          makezero ./... 2>&1|grep -v assign|grep -v copy > hit.log || (test $? -eq 1) && exit 0

          cat hit.log

          exit `grep -c 'append to slice' hit.log`
