name: submit-repos
run-name: "submit ${{inputs.count }} repo from ${{inputs.source}} for ${{inputs.workflow}}"

on:
  workflow_dispatch:
    inputs:
      source:
        description: |
          can be 'top.txt' or  'awesome.txt' or some 'https://xxx' download link
          Default 'top.txt'
        default: "top.txt"
      count:
        description: |
          total submit repo count
          Default '1000'
        default: "1000"
      workflow:
        description: |
          the workflow to submit with each repo
          Default 'go-linter-runner.yml'
        default: "go-linter-runner.yml"
      workflow_ref:
        description: |
          the workflow ref barnch to run
          Default ''
        default: ''

permissions:
  actions: write

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Submit repos
        uses: alingse/go-linter-runner@main
        with:
          action: submit
          submit_source_file: ${{ inputs.source }}
          submit_repo_count: ${{ inputs.count }}
          submit_workflow: ${{ inputs.workflow }}
          submit_workflow_ref: ${{ inputs.workflow_ref }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
