name: submit-repos
run-name: "submit repo urls for run-repo.yml"

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Example -> go-linter-runner submit 10 repos
        uses: alingse/go-linter-runner@main
        with:
          action: submit
          submit_source_file: top.txt
          submit_repo_count: 10
          submit_workflow: run-repo.yml
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
