name: submit-repos
run-name: "submit repo urls for run-repo.yml"

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger run-repo workflow
        run: gh workflow run run-repo.yml --ref main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
